services:
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: agronomy
  
  server:
    build: .
    links:
      - db
    command: ./build/server --port=80 --dbhost=host.docker.internal --dbport=5432 --dbuser=postgres --dbpassword=example --dbname=agronomy
    ports:
      - 3490:80
    depends_on:
      - db